api/isd/ISD-ReportServices-ejb/pom.xml, tools/openshift/api.bc.yaml
Reverts bcgov/EDUC-GRAD-REPORT-API#19
=> Revert "Develop/km"

api/isd/ISD-ReportServices-ejb/pom.xml, tools/openshift/api.bc.yaml
Reverts bcgov/EDUC-GRAD-REPORT-API#21
=> Revert "Revert "Develop/km""

api/pom.xml, api/src/main/java/ca/bc/gov/educ/grad/report/dto/impl/StudentImpl.java, api/src/main/resources/reports/SchoolGraduation.jrxml, api/src/main/resources/reports/SchoolNonGraduation.jrxml, api/src/main/resources/reports/StudentNonGrad.jrxml, api/src/main/resources/reports/resources/styles/ETS.jrtx, api/src/main/resources/reports/subreports/transcript/sections/BC1950-IND/HEADER_BC1950-IND.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC1950-PUB/HEADER_BC1950-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC1986-IND/HEADER_BC1986-IND.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC1986-PUB/HEADER_BC1986-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC1996-IND/HEADER_BC1996-IND.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC1996-PUB/HEADER_BC1996-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2004-IND/HEADER_BC2004-IND.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2004-PUB/HEADER_BC2004-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2018-IND/HEADER_BC2018-IND.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2018-OFF/HEADER_BC2018-OFF.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2018-PF/HEADER_BC2018-PF.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2018-PUB/HEADER_BC2018-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/SCCP-EN/HEADER_SCCP-EN.jrxml, api/src/main/resources/reports/subreports/transcript/sections/SCCP-FR/HEADER_SCCP-FR.jrxml, api/src/main/resources/reports/subreports/transcript/sections/YU1950-PUB/HEADER_YU1950-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/YU1986-PUB/HEADER_YU1986-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/YU1996-PUB/HEADER_YU1996-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/YU2004-PUB/HEADER_YU2004-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/YU2018-PUB/HEADER_YU2018-PUB.jrxml, api/src/test/resources/json/studentTranscriptReportRequest-BC1950-IND.json, api/src/test/resources/json/studentTranscriptReportRequest-BC1986-IND.json
Add report desctiption to Projected Non-Grad Summary Report (NONGRADPRJ)
=> GRAD2-1618

api/src/main/java/ca/bc/gov/educ/grad/report/api/client/AchievementCourse.java, api/src/main/resources/reports/SchoolGraduation.jrxml
=> GRAD2-1559

api/src/main/java/ca/bc/gov/educ/grad/report/api/client/Student.java, api/src/main/java/ca/bc/gov/educ/grad/report/dao/GradDataConvertionBean.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/impl/StudentImpl.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/impl/StudentInfoImpl.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/reports/data/adapter/BusinessEntityAdapter.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/reports/data/impl/Student.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/reports/jasper/impl/JRDataSourceFactory.java, api/src/main/java/ca/bc/gov/educ/grad/report/model/student/Student.java, api/src/main/java/ca/bc/gov/educ/grad/report/model/student/StudentInfo.java, api/src/main/java/ca/bc/gov/educ/grad/report/service/impl/GradReportServiceImpl.java, api/src/main/resources/reports/Achievement.jrxml, api/src/test/resources/json/studentAchievementReportRequest.json
=> GRAD2-1683

api/src/main/java/ca/bc/gov/educ/grad/report/dao/GradDataConvertionBean.java
Add citizenship code to the student "clob" as part of the graduation algorithm run
=> GRAD2-1734

api/src/main/java/ca/bc/gov/educ/grad/report/model/graduation/GraduationProgramCode.java
FLYWAY updates to PROGRAM Descriptions
=> GRAD2-1644

api/src/main/resources/reports/subreports/transcript/sections/YU1986-PUB/BG_YU1986-PUB_INTERIM.jrxml, api/src/main/resources/reports/subreports/transcript/sections/YU1986-PUB/DETAIL_NONPROV_YU1986-PUB_INTERIM.jrxml, api/src/test/resources/json/studentTranscriptReportRequest-YU1986-PUB.json
Interim Preview for Yukon not working
=> GRAD2-1798

api/src/main/resources/db/migration/1.0/V1.0.69__DML-UPDATE-SIGNATURE_BLOCK_TYPE.sql
GRAD2-1864, 1845 - FLYWAY changes - SIGNATURE BLOCK TYPE, CERTIFICATE_TYPE_CODE
=> GRAD2-1864, 1845 - FLYWAY changes - SIGNATURE BLOCK TYPE, CERTIFICATE_TYPE_CODE

api/src/main/java/ca/bc/gov/educ/grad/report/api/controller/BaseController.java, api/src/main/java/ca/bc/gov/educ/grad/report/api/service/utils/BaseTransformer.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/reports/jasper/TranscriptCalculator.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/reports/jasper/impl/ReportImpl.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/reports/util/InheritableResourceBundle.java, api/src/main/java/ca/bc/gov/educ/grad/report/service/impl/StudentAchievementServiceImpl.java, api/src/main/java/ca/bc/gov/educ/grad/report/service/impl/StudentTranscriptServiceImpl.java, api/src/main/resources/reports/SchoolLabel.jrxml
=> Alignment adjustment of School Labels.

api/src/main/resources/application.yaml
Fixed the Report API launching Issue.
=> Report API failed launching

api/src/main/resources/reports/subreports/transcript/sections/BC1996-IND/SUMMARY_BC1996-IND.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC1996-PUB/SUMMARY_BC1996-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2004-IND/SUMMARY_BC2004-IND.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2004-PUB/SUMMARY_BC2004-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2018-IND/SUMMARY_BC2018-IND.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2018-OFF/SUMMARY_BC2018-OFF.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2018-PF/SUMMARY_BC2018-PF.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2018-PUB/SUMMARY_BC2018-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2023-IND/SUMMARY_BC2023-IND.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2023-OFF/SUMMARY_BC2023-OFF.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2023-PF/SUMMARY_BC2023-PF.jrxml, api/src/main/resources/reports/subreports/transcript/sections/BC2023-PUB/SUMMARY_BC2023-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/YU1996-PUB/SUMMARY_YU1996-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/YU2004-PUB/SUMMARY_YU2004-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/YU2018-PUB/SUMMARY_YU2018-PUB.jrxml, api/src/main/resources/reports/subreports/transcript/sections/YU2023-PUB/SUMMARY_YU2023-PUB.jrxml
Modifications to Transcript BACK
=> GRAD2-1977

api/src/main/java/ca/bc/gov/educ/grad/report/api/client/Pen.java, api/src/main/java/ca/bc/gov/educ/grad/report/api/client/Student.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/impl/StudentImpl.java, api/src/main/java/ca/bc/gov/educ/grad/report/model/student/PersonalEducationNumber.java, api/src/main/resources/reports/DistrictDistYearEndCred.jrxml, api/src/main/resources/reports/SchoolDistYearEndCred.jrxml, api/src/main/resources/reports/SchoolDistYearEndTran.jrxml, api/src/test/resources/json/schoolDistributionYearEndReportRequest.json
Fixed possible NPE on compare Student Objects
=> Updated School Report Header

api/src/main/resources/reports/SchoolDistYearEndTran.jrxml
GRAD2-2259: task is completed.
=> GRAD2-2259: task is completed.

api/src/main/resources/db/migration/1.0/V1.0.96__DML-INSUPD_DATA-report_type_code.sql
=> GRAD2-2284, GRAD2-2290

api/pom.xml, api/src/main/java/ca/bc/gov/educ/grad/report/dao/CertificateTypeCodeRepository.java, api/src/main/java/ca/bc/gov/educ/grad/report/dao/GradDataConvertionBean.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/impl/TranscriptCourseImpl.java, api/src/main/java/ca/bc/gov/educ/grad/report/model/transcript/TranscriptCourse.java, api/src/main/java/ca/bc/gov/educ/grad/report/service/impl/StudentTranscriptServiceImpl.java
=> Grad release 1.10.0

api/src/main/java/ca/bc/gov/educ/grad/report/dto/reports/bundle/decorator/AchievementReportDecorator.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/reports/bundle/decorator/CertificateReportDecorator.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/reports/bundle/decorator/TranscriptReportDecorator.java, api/src/main/resources/reports/PackingSlip.jrxml, api/src/test/resources/json/packingSlipReportRequest.json
Fix packing slip jasper file to accommodate address line 2
=> GRAD2-2403

api/src/main/resources/reports/subreports/certificate/AB.jrxml, api/src/main/resources/reports/subreports/certificate/AIB.jrxml, api/src/main/resources/reports/subreports/certificate/EB.jrxml, api/src/main/resources/reports/subreports/certificate/EIB.jrxml, api/src/main/resources/reports/subreports/certificate/FB.jrxml, api/src/main/resources/reports/subreports/certificate/FNAB.jrxml, api/src/main/resources/reports/subreports/certificate/FNB.jrxml, api/src/main/resources/reports/subreports/certificate/OB.jrxml, api/src/main/resources/reports/subreports/certificate/SB.jrxml, api/src/main/resources/reports/subreports/certificate/SCB.jrxml, api/src/main/resources/reports/subreports/certificate/SCFNB.jrxml, api/src/main/resources/reports/subreports/certificate/SCIB.jrxml
HD-23007-P3 GRAD Incident: Blank Certificate orders are Missing Signatures (Superintendent, Inspector, FN Governing Authority)
=> GRAD2-2387

api/src/main/resources/reports/Transcript_BC1950-IND.jrxml, api/src/main/resources/reports/Transcript_BC1950-PUB.jrxml, api/src/main/resources/reports/Transcript_BC1986-IND.jrxml, api/src/main/resources/reports/Transcript_BC1986-PUB.jrxml, api/src/main/resources/reports/Transcript_BC1996-IND.jrxml, api/src/main/resources/reports/Transcript_BC1996-PUB.jrxml, api/src/main/resources/reports/Transcript_BC2004-IND.jrxml, api/src/main/resources/reports/Transcript_BC2004-PUB.jrxml, api/src/main/resources/reports/Transcript_BC2018-IND.jrxml, api/src/main/resources/reports/Transcript_BC2018-OFF.jrxml, api/src/main/resources/reports/Transcript_BC2018-PF.jrxml, api/src/main/resources/reports/Transcript_BC2018-PUB.jrxml, api/src/main/resources/reports/Transcript_BC2023-IND.jrxml, api/src/main/resources/reports/Transcript_BC2023-OFF.jrxml, api/src/main/resources/reports/Transcript_BC2023-PF.jrxml, api/src/main/resources/reports/Transcript_BC2023-PUB.jrxml, api/src/main/resources/reports/Transcript_NOPROG.jrxml, api/src/main/resources/reports/Transcript_SCCP-EN.jrxml, api/src/main/resources/reports/Transcript_SCCP-FR.jrxml, api/src/main/resources/reports/Transcript_YU1950-PUB.jrxml, api/src/main/resources/reports/Transcript_YU1986-PUB.jrxml, api/src/main/resources/reports/Transcript_YU1996-PUB.jrxml, api/src/main/resources/reports/Transcript_YU2004-PUB.jrxml, api/src/main/resources/reports/Transcript_YU2018-PUB.jrxml, api/src/main/resources/reports/Transcript_YU2023-PUB.jrxml, api/src/test/java/ca/bc/gov/educ/grad/report/api/test/service/GradReportApiTranscriptServiceTests.java, api/src/test/resources/json/studentTranscriptReportRequest-YU2023-PUB-PREVIEW.json
(GRAD) - Incident: XML Preview needs to show Last Updated Date instead of an Issue Date
=> GRAD2-2513

api/src/main/java/ca/bc/gov/educ/grad/report/api/client/GradProgram.java, api/src/main/java/ca/bc/gov/educ/grad/report/dao/GradDataConvertionBean.java, api/src/main/java/ca/bc/gov/educ/grad/report/dto/impl/GradProgramImpl.java, api/src/main/java/ca/bc/gov/educ/grad/report/model/graduation/GradProgram.java, api/src/main/java/ca/bc/gov/educ/grad/report/service/impl/StudentAchievementServiceImpl.java, api/src/main/java/ca/bc/gov/educ/grad/report/service/impl/StudentTranscriptServiceImpl.java, api/src/test/java/ca/bc/gov/educ/grad/report/api/test/service/GradReportApiTranscriptServiceTests.java
=> GRAD2-2525: task is complete.

api/src/main/resources/db/migration/1.0/V1.0.101__DML-UPDATE_TABLE-SIGNATURE_BLOCK_TYPE.sql
=> Grad2-2569 Update MOE_ADM signature block type label and description

api/src/main/java/ca/bc/gov/educ/grad/report/dto/GradReportSignatureImage.java, api/src/main/java/ca/bc/gov/educ/grad/report/entity/GradReportSignatureImageEntity.java, api/src/test/java/ca/bc/gov/educ/grad/report/api/test/controller/StudentReportSignatureImageControllerTest.java
Done with adding organization name to digital signature images endpoint
=> Grad2-2843 Added New Field to Endpoint

api/src/main/resources/db/migration/1.0/V1.0.112__DML-INSERT_DATA-REPORT_TYPE_CODE.sql
=> Inserted new Report Type Codes

api/src/main/java/ca/bc/gov/educ/grad/report/dto/reports/data/impl/Certificate.java
GRAD2-2921: fixed the wrong issued date in certificate.
=> GRAD2-2921: fixed the wrong issued date in certificate.

api/src/main/java/ca/bc/gov/educ/grad/report/dto/BaseModel.java
=> Signature images updated dates displaying correctly

api/src/main/java/ca/bc/gov/educ/grad/report/dto/impl/TranscriptCourseImpl.java, api/src/main/java/ca/bc/gov/educ/grad/report/service/impl/StudentTranscriptServiceImpl.java
GRAD2-2905: fixed the equal interim issue for OPEN program in xml preview.
=> GRAD2-2905: fixed the equal interim issue for OPEN program in xml preview.

api/src/main/java/ca/bc/gov/educ/grad/report/api/client/TraxSchool.java, api/src/main/resources/application.yaml, api/src/test/resources/application.yaml
=> GRAD2-2761: task is complete.

api/src/main/java/ca/bc/gov/educ/grad/report/api/client/TraxSchool.java
GRAD2-2761: districtId is newly added into School Clob.
=> GRAD2-2761: districtId is newly added into School Clob.

api/src/main/java/ca/bc/gov/educ/grad/report/dto/impl/PostalAddressImpl.java, api/src/main/resources/isotraxmap.properties, api/src/test/resources/data/student_grad_data.json, api/src/test/resources/json/districtDistributionYearEndNonGradReportRequest.json, api/src/test/resources/json/districtDistributionYearEndReportRequest.json, api/src/test/resources/json/schoolLabelReportRequest.json, api/src/test/resources/json/studentAchievementReportRequest.json, api/src/test/resources/json/studentCertificateReportRequest-E.json, api/src/test/resources/json/studentCertificateReportRequest-F.json, api/src/test/resources/json/studentCertificateReportRequest-FN.json, api/src/test/resources/json/studentTranscriptReportRequest-BC1986-PUB.json, api/src/test/resources/json/studentTranscriptReportRequest-BC2018-IND.json, api/src/test/resources/json/studentTranscriptReportRequest-BC2018-OFF.json, api/src/test/resources/json/studentTranscriptReportRequest-BC2018-PUB-23.json, api/src/test/resources/json/studentTranscriptReportRequest-BC2018-PUB.json, api/src/test/resources/json/studentTranscriptReportRequest-BC2023-OFF.json, api/src/test/resources/json/studentTranscriptReportRequest-NOPROG.json, api/src/test/resources/json/studentTranscriptReportRequest-SCCP-EN-PREVIEW.json, api/src/test/resources/json/studentTranscriptReportRequest-SCCP-EN.json
GRAD2-3288 - School Address Labels have incorrect format
=> GRAD2-3288 - School Address Labels have incorrect format

api/src/main/resources/reports/subreports/certificate/SC.jrxml, api/src/main/resources/reports/subreports/certificate/SCB.jrxml, api/src/main/resources/reports/subreports/certificate/SCF.jrxml, api/src/main/resources/reports/subreports/certificate/SCFB.jrxml, api/src/main/resources/reports/subreports/certificate/SCFN.jrxml, api/src/main/resources/reports/subreports/certificate/SCFNB.jrxml, api/src/main/resources/reports/subreports/certificate/SCFNO.jrxml, api/src/main/resources/reports/subreports/certificate/SCFO.jrxml, api/src/main/resources/reports/subreports/certificate/SCI.jrxml, api/src/main/resources/reports/subreports/certificate/SCIB.jrxml, api/src/main/resources/reports/subreports/certificate/SCIO.jrxml, api/src/main/resources/reports/subreports/certificate/SCO.jrxml
GRAD2-3371: task is completed.
=> GRAD2-3371: task is completed.

api/src/main/resources/db/migration/1.0/V1.0.138__DML-UPDATE_TABLE-CERTIFICATE_TYPE_CODE.sql
=> Grad2-3228 Period is removed from description

api/src/main/resources/reports/Achievement.jrxml
=> TVR header text correction
